version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: shortener_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345678
      POSTGRES_DB: shortener_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - shortener-network

  redis:
    image: redis:alpine
    container_name: shortener_redis
    ports:
      - "6379:6379"
    networks:
      - shortener-network

volumes:
  postgres_data:

networks:
  shortener-network:
    driver: bridge